services:
    flask_test_project:
        build: ./
        container_name: flask_test_project_container
        environment:
            - FLASK_APP=FlaskTestProject/app.py
            - FLASK_DEBUG=development
            - DATABASE_URL=postgresql://{PGUSER}:{PGPASSWORD}@{db_host}:{PORT}/{DATABASE}
        ports:
            - '5000:5000'
        volumes:
            - ./.env:/usr/src/app/.env
        depends_on:
            -   postgres

    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_DB: "postgres_db"
            POSTGRES_USER: "PGUSER" #Enter your Postgres username here
            POSTGRES_PASSWORD: "PGPASSWORD" #Enter your password here
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        expose:
            - "5432"

volumes:
    postgres_volume:
